### ISSUE TITLE
Handle Poetry(?) version specifiers.

### ISSUE THREAD

**Issue by dsully** [stvnksslr/uv-migrator#16]
These are valid specifiers:

```toml
[tool.poetry.group.test.dependencies]
blue = ">=0.9.1"
```

`uv-migrator` fails with: 
```shell
[2024-10-30T14:52:09Z ERROR uv_migrator] Error during migration: Failed to add Main dependencies: error: Failed to parse: `blue==>=0.9.1`
      Caused by: no such comparison operator "==>=", must be one of ~= == != <= >= < > ===
    blue==>=blue
               ^^^^^^^^^^
```

I *think* the issue is here: https://github.com/stvnksslr/uv-migrator/blob/0f833495c67abd956c0533970479fbdf28739f74/src/migrator/mod.rs?plain=1#L86

But I'm also wondering if using a combination of  https://crates.io/crates/requirements and https://crates.io/crates/pep440_rs would make this a bit easier?

Thanks

**Comment by stvnksslr** [comment]
Ah i know exactly whats causing this, ill have it fixed in a moment.

I hadn't seen the requirements crate actually ill give it a try that could simplify a lot of the ingestion.

**Comment by stvnksslr** [comment]
fixed as of the latest release, will leave open for a bit to confirm
